emojinum = {1:"1️⃣", 2:"2️⃣", 3:"3️⃣", 4:"4️⃣", 5:"5️⃣", 6:"6️⃣", 7:"7️⃣", 8:"8️⃣", 9:"9️⃣", 10:"🔟"}
allquiz = {"1": ("What was the name of the Ethiopian Wolf before they knew it was related to wolves?", 
                ("Simien Jackel", True), 
                ("Ethiopian Coyote", False), 
                ("Amharic Fox", False), 
                ("Canis Simiensis", False), 
                {'True':"1️⃣"}), 
            "2": ("What scientific suborder does the family Hyaenidae belong to", 
                ("Haplorhini", False), 
                ("Feliformia", True), 
                ("Ciconiiformes", False),
                ("Caniformia", False),
                {'True':"2️⃣"}),
            "3": ('ม้าลายมีลายสีอะไร',
                ('สีดำ', False),
                ('สีขาวเกือบเทา', False),
                ('สีขาว', True),
                ('สีเทา', False),
                {'True':"3️⃣"}),
            "4": ('"บักสีดา" ในภาษาอีสาน หมายถึงผลไม้ชนิดใด', 
                ('กล้วย', False),
                ('ส้ม', False),
                ('ฝรั่ง', True),
                ('มะละกอ', False),
                {'True':"3️⃣"}),
            "5": ("In Roman Numerals, what does XL equate to?",
                ("15", False),
                ("60", False),
                ("90", False),
                ("40", True),
                {'True':"4️⃣"})}}
