emojinum = ["0️⃣", "1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣", "9️⃣", "🔟"]
allquiz = {"1": ("What was the name of the Ethiopian Wolf before they knew it was related to wolves?", 
                ("Simien Jackel", True), 
                ("Ethiopian Coyote", False), 
                ("Amharic Fox", False), 
                ("Canis Simiensis", False)), 
            "2": ("What scientific suborder does the family Hyaenidae belong to", 
                ("Haplorhini", False), 
                ("Feliformia", True), 
                ("Ciconiiformes", False),
                ("Caniformia", False)),
            "3": ("Who Asked?",
                ("David", False),
                ("Joe Mama", False), 
                ("No One", True), 
                ("John", False), 
                ("Jane", False), 
                ("Dennis", False)), 
            "4": ("Which animal have more than 3 legs?", 
                ("Dog", True), 
                ("Cat", True), 
                ("Spider", True)),
            "5": ("Which is the shape of earth?", 
                ("Sphere", True), 
                ("Flat", False), 
                ("Dinosaur", False),
                ("Dinosaur", False), 
                ("Dinosaur", False), 
                ("Dinosaur", False), 
                ("Dinosaur", False), 
                ("Dinosaur", False), 
                ("Dinosaur", False), 
                ("Donut", False)),
            "6": ("Rose is Red?",
                ("True", True),
                ("False", False)),
            }
